
# DO NOT TOUCH
config-version: 3

# Change default stats here
# Regen unit: <resource> per second
default:
    max-mana: 20
    max-stamina: 20
    mana-regeneration: 0.5
    stamina-regeneration: 0.5

# The interval at which regeneration should happen in ticks.
# Default value is 10 ticks which is the same as half a second.
refresh-rate: 10

# The percentage of their max mana/stamina which players
# get as mana/stamina when logging in for the first time
login-ratio:
    mana: 75
    stamina: 75

# Edit here the character used in the resource bars
# in the %mana_<mana/stamina>_bar% placeholder.
resource-bar:
    mana:
        char: █
        length: 20
        colors:
            # You can use HEX colors too:
            # whole: \#223344
            whole: AQUA
            half: DARK_AQUA
            empty: WHITE
    stamina:
        char: █
        length: 20
        colors:
            whole: GREEN
            half: DARK_GREEN
            empty: WHITE
